Feat/add version 8 to 9 converter
GIScience/ors-config-migration pull request #6
Opened 2024-11-15 13:18 UTC by TheGreatRefrigerator

2024-12-02 17:00 UTC, TheGreatRefrigerator commented
Currently, graphs_root_path is just removed without further info.
The final output should contain a bit more of what's new and where to find docu for it

2024-12-03 15:28 UTC, jhaeu commented
From 8 -> 9 please migrate 

`ors.engine.graphs_root_path` -> `ors.engine.profile_default.graph_path`

2024-12-03 15:33 UTC, jhaeu requested changes

2024-12-04 10:59 UTC, merydian commented on migrate.py
> +        if_exists_move_to(x, f'ors.{level_string}.graphs_root_path', f'ors.{level_string}.profile_default.graphs_root_path')
This is the only occurrence

2024-12-04 13:27 UTC, jhaeu commented on migrate.py
> +        if_exists_move_to(x, f'ors.{level_string}.graphs_root_path', f'ors.{level_string}.profile_default.graphs_root_path')
Sure? Is there no model for v9 that needs to be adapted?

2024-12-04 13:56 UTC, jhaeu commented
I found out that when migrating v7 -> v8 `graphs_root_path` gets lost. This seems to be an old issue.

This peace of information should be located in

* v7 `ors.services.routing.profiles.default_params.graphs_root_path`
* v8 `ors.engine.graphs_root_path`
* v9 `ors.engine.profile_default.graph_path`

2024-12-04 15:46 UTC, TheGreatRefrigerator commented
restructured and fixed missing things in 9 allow extras model

2024-12-04 15:47 UTC, merged